import { ESTADO_CIVIL } from '../types/estado-civil.enum'

export const ESTADO_CIVIL_LISTA = [
  ESTADO_CIVIL.CASADO,
  ESTADO_CIVIL.DIVORCIADO,
  ESTADO_CIVIL.SEPARADO,
  ESTADO_CIVIL.SOLTEIRO,
  ESTADO_CIVIL.VIUVO
]
